<meta name="google-site-verification" content="{{site.google_validation}}" />
<meta name="msvalidate.01" content="{{site.bing_validation}}" />
<meta name="alexaVerifyID" content="{{site.alexa_validation}}" />
<link rel="apple-touch-icon" sizes="57x57" href="apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="144x144" href="apple-touch-icon-144x144.png" />
<link href="/favicon.ico" rel="shortcut icon" />
<link rel="alternate" type="application/atom+xml" title="The Digital Rosetta Stone: Site Updated" href="https://github.com/fileformat/rosetta-www/commits/master.atom" />

