<% if @item[:draft] or @item[:noindex] %>	<meta name="robots" content="NOINDEX" />
<% end %>	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700,700italic" rel="stylesheet" type="text/css" />
	<link type="text/css" rel="stylesheet" href="/css/bootstrap.css" />
	<link type="text/css" rel="stylesheet" href="/css/font-awesome.css" />
	<style type="text/css">
	  body {
		padding-top: 20px;
		padding-bottom: 40px;
	  }

	  h1, h2, h3, h4 { font-weight: bold }

	  /* Custom container */
	  .container-narrow {
		margin: 0 auto;
		max-width: 960px;
	  }
	  .container-narrow &gt; hr {
		margin: 30px 0;
	  }

	  /* Main marketing message and sign up button */
	  .jumbotron {
		xmargin: 60px 0;
		text-align: center;
	  }
	  .jumbotron h1 {
		font-size: 54px;
		line-height: 1;
	  }
	  .jumbotron ul {
		text-align:left;

	  }

	  /* Supporting marketing content */
	  .marketing {
		margin: 60px 0;
	  }
	  .marketing p + h4 {
		margin-top: 28px;
	  }
	  .drs-entry-row {
	  	  cursor: pointer;
	  }

	  #drs-download {
	  	  margin: 10px 0px;
	  	  text-align: center;
	  }
	</style>

