#
# _config.yml for andrew.marcuse.info
#

exclude: [ "CNAME", "README.md", "LICENSE.txt", "tmp", "*.sh", "**/*_src*" ]
permalink: /files/:year/:title.html
production_url: https://www.digitalrosetta.org
title: The Digital Rosetta Stone
markdown: kramdown
gems:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

google_analytics_id: UA-328425-34
google_validation: yE4nsRE5eUYG_Ahhgh-UuM4mA4pakFdTF2jR-xj9WXo
bing_validation: E90DBA4A9D3D37F1056E64E5604A7A0D
yandex_validation: 243e677e94eb7925
